### PR TITLE
Allow compilation with ghc 8.10.7

### PR DESCRIPTION
**Pull request by nitinprakash96**
Need to allow GHC 8.10.7.
Current build on `master`:
```
λ  servant-hmac-auth git:(master) ✗ stack build --resolver lts-18.21

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for servant-hmac-auth-0.1.3:
    base64-bytestring-1.1.0.0 from stack configuration does not match ^>=1.0  (latest matching version is 1.0.0.3)
needed since servant-hmac-auth is a build target.

Some different approaches to resolving this:

  * Set 'allow-newer: true' in /Users/nitin/.stack/config.yaml to ignore all version constraints and build anyway.

  * Recommended action: try adding the following to your extra-deps in /Users/nitin/Documents/temp/servant-hmac-auth/stack.yaml:

- base64-bytestring-1.0.0.3@sha256:d5027ea6d63eab27cfa34eb1f5a05b6a5ee521dd176a06da3f7d80e117a88259,2352

```

### CODE REVIEW

File: .github/workflows/haskell-ci.yml [hunk 1]
```diff
@@ -1,43 +1,44 @@
...
-    - name: Build
-      run: |
-        stack build --test --bench --no-run-tests --no-run-benchmarks
-    - name: Test
-      run: |
-        stack test
\ No newline at end of file
+      - name: Install dependencies
+        run: |
+          stack build --test --bench --no-run-tests --no-run-benchmarks --only-dependencies
```
Comment (jhrcek) [inline .github/workflows/haskell-ci.yml:38]: If you want these stack commands to use the stack yaml files, you'll have to specify it on cli,
something like `stack build .... --stack-yaml stack-${{ matrix.ghc }}`

Also if you want to use the ghc installed by `haskell/actions/setup@v1` 
you should add `--system-ghc` to all the stack commands (otherwise stack will install its own GHC and ignore the ghc installation provided by that setup action.

And

Comment (jhrcek) [reply .github/workflows/haskell-ci.yml:38]: You can see it's downloading ghc-8.8.3 in 8.10.7 job
Screenshot from 2022-01-04 13-04-39

**Review by jhrcek — COMMENTED** [review]
Please add cli arguments to use `--system-ghc` and `--stack-yaml stack-${{ matrix.ghc }}.yaml` to all stack invocations. You'll also probably need to rename stack.yaml to stack-8.8.4.yaml and use some resolver that depends on 8.8.4 (e.g. latest 17: https://www.stackage.org/lts-17.15)

**Review by jhrcek — CHANGES_REQUESTED** [review]
Sorry, forgot to click "request changes"

File: .gitignore [hunk 2]
```diff
@@ -23,6 +23,7 @@ cabal.project.local
 .HTF/
 # Stack
 .stack-work/
+*.yaml.lock
```
Comment (turboMaCk) [inline .gitignore:26]: seems a bit too of a wildcard. Which file do you want to exclude? `stack.yaml.lock` or does it generate `stack-version.yaml.lock` files as well? (I'm not sure).

File: .github/workflows/haskell-ci.yml (hunk 1 above)
Comment (nitinprakash96) [reply .github/workflows/haskell-ci.yml]: Thanks for pointing this out. I did not realise this was happening.

Comment (turboMaCk) [reply .github/workflows/haskell-ci.yml]: I like to use lazy approach to this. Rather than being forced to check everything all the time use the workflow where it's hard to miss the problem. If you want to make something build with new version of compiler, start by replicating compilation error in ci. Only then attempt to fix it.

**Comment by jhrcek** [comment]
It's possible you'll no longer be able to build with GHC 8.6.5, due to constraints introduced in https://github.com/Holmusk/servant-hmac-auth/commit/75599c259e276220d1bf90a4e200a55a22eb901e

In that case I'd recommend simply dropping ghc 8.6.5.
Also I'd recommend using GHC 8.8.4 (latest in 8.8 series instead of 8.8.3).

**Comment by jhrcek** [comment]
Or alternatively you can just add appropriate extra-deps to stack-8.6.5.yaml.

File: .github/workflows/haskell-ci.yml [hunk 3]
```diff
@@ -1,43 +1,45 @@
...
 
-    - uses: haskell/actions/setup@v1
-      name: Setup Haskell Stack
-      with:
-        ghc-version: ${{ matrix.ghc }}
-        stack-version: ${{ matrix.stack }}
+      - uses: haskell/actions/setup@v1
+        name: Setup Haskell Stack
+        with:
+          ghc-version: ${{ matrix.ghc }}
```
Comment (jhrcek) [inline .github/workflows/haskell-ci.yml:28]: You still need to define matrix.ghc for the setup to work

File: .gitignore (hunk 2 above)
Comment (nitinprakash96) [reply .gitignore]: Previously there was `stack.yaml.lock` as well as `stack-*.yaml.lock`. I resorted to `*.yaml.lock` in order to tackle both at once but I've completely removed `stack.yaml` after the latest commit. So I've updated the wildcard to only track `stack-*` lock files.

File: stack-8.8.4.yaml [hunk 4]
```diff
@@ -0,0 +1,7 @@
+resolver: lts-16.2
```
Comment (jhrcek) [inline stack-8.8.4.yaml:1]: this resolver is based on ghc 8.8.3 (as you can see on its page: https://www.stackage.org/lts-16.2)
so the 8.8.4 in the file name is a bit misleading.
I'd just change this line to 
```suggestion
resolver: lts-16.31
```
which is the latest 8.8.4 based resolver

File: .github/workflows/haskell-ci.yml (hunk 3 above)
Comment (nitinprakash96) [reply .github/workflows/haskell-ci.yml]: I've removed this altogether and resorted to `{{ matrix.stack-yaml }}`.

File: .github/workflows/haskell-ci.yml [hunk 5]
```diff
@@ -1,43 +1,80 @@
...
+
+      - uses: actions/cache@v2.1.6
+        name: Cache ~/.stack
+        with:
+          path: ~/.stack
+          key: ${{ runner.os }}-${{ matrix.stack-yaml }}
+
+      - name: Install dependencies
+        run: |
+          stack build --stack-yaml ${{ matrix.stack-yaml }} --test --bench --no-run-tests --no-run-benchmarks --only-dependencies --system-ghc
```
Comment (jhrcek) [inline .github/workflows/haskell-ci.yml:74]: Since you're not setting up system ghc installation (you don't have `ghc-version: ${{ matrix.ghc }}` under haskell/action/setup in stack jobs)
it makes no sense to use system GHC.

Choose one of these 2 options:
1. install ghc in the setup by including ghc-version in the setup step + use --system-ghc flag 
OR
2. don't install ghc (so stack will install it itself when you run it for the first time) and remove --system-ghc flag.

**Review by jhrcek — COMMENTED** [review]
Almost there :smile:

File: servant-hmac-auth.cabal [hunk 6]
```diff
@@ -16,6 +16,7 @@ extra-source-files:  README.md
                    , CHANGELOG.md
 tested-with:         GHC == 8.6.5
                      GHC == 8.8.3
+                     GHC == 8.10.7
```
Comment (jhrcek) [inline servant-hmac-auth.cabal:19]: Change tested-with to GHC 8.8.4 please

File: .github/workflows/haskell-ci.yml [hunk 7]
```diff
@@ -1,43 +1,80 @@
...
 
 jobs:
+  cabal:
+    name: cabal ${{ matrix.os }} / ghc ${{ matrix.ghc }}
+    runs-on: ${{ matrix.os }}
+    strategy:
+      matrix:
+        os:
+          - ubuntu-latest
+        cabal: [3.4]
```
Comment (jhrcek) [inline .github/workflows/haskell-ci.yml:17]: I'd switch to latest cabal 3.6 just to be as "modern" as possible :smile:

**Review by jhrcek — APPROVED** [review]
Looks great, than you!
I love the consistent formatting :+1:
